### ISSUE TITLE
Backup fails in case DB file doesn't exist

### ISSUE THREAD

**Issue by madhaven** [madhaven/proTracker#96]
In case of Backups existing and the actual db file missing, the app seems to have trouble setting up the db tables.
Investigate this with the help of these logs:

```log
2024-02-09T14:18:16.283Z DEBUG: ConfigService():read [object Object]
2024-02-09T14:18:16.284Z LOG: DatabaseService: DB missing, restoring from backup
2024-02-09T14:18:16.284Z ERROR: DatabaseService: DB restore failed
2024-02-09T14:18:16.336Z DEBUG: backend event handlers registered
2024-02-09T14:18:16.430Z DEBUG: TaskProvider: getallTasks
2024-02-09T14:18:16.431Z ERROR: Trace: TaskProvider: getAllTasks Error: SQLITE_ERROR: no such table: task
--> in Database#all('SELECT t.id as id, t.summary, t.project_id as project_id, t.parent_id, p.name as project_name, sl.date_time as date_time, s.id as status_id, s.status as status_name FROM task t INNER JOIN project p ON t.project_id=p.id INNER JOIN (SELECT task_id, MAX(date_time) AS date_time, status_id FROM status_log GROUP BY task_id) sl ON t.id=sl.task_id INNER JOIN status s ON s.id=sl.status_id', [], [Function (anonymous)])
    at .\Scripts\Services\DatabaseService.js:111:16
    at new Promise (<anonymous>)
    at DatabaseService.fetch (.\Scripts\Services\DatabaseService.js:109:16)
    at TaskProvider.getAllTasks (.\Scripts\Providers\TaskProvider.js:57:46)
    at loadLogsHandler (.\Scripts\handlers.js:38:25)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89595)
    at WebContents.emit (node:events:513:28) {
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
    at TaskProvider.getAllTasks (.\Scripts\Providers\TaskProvider.js:66:21)
    at async loadLogsHandler (.\Scripts\handlers.js:38:16)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579)
2024-02-09T14:18:16.432Z DEBUG: StatusLogProvider: getAllLogs
2024-02-09T14:18:16.433Z ERROR: Trace: StatusLogProvider: getAllLogs Error: SQLITE_ERROR: no such table: status_log
--> in Database#all('SELECT id, task_id, status_id, date_time FROM status_log;', [], [Function (anonymous)])
    at .\Scripts\Services\DatabaseService.js:111:16
    at new Promise (<anonymous>)
    at DatabaseService.fetch (.\Scripts\Services\DatabaseService.js:109:16)
    at StatusLogProvider.getAllLogs (.\Scripts\Providers\StatusLogProvider.js:31:46)
    at loadLogsHandler (.\Scripts\handlers.js:39:25)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579) {
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
    at StatusLogProvider.getAllLogs (.\Scripts\Providers\StatusLogProvider.js:40:21)
    at async loadLogsHandler (.\Scripts\handlers.js:39:15)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579)
2024-02-09T14:18:16.433Z DEBUG: ProjectProvider: getAll
2024-02-09T14:18:16.434Z ERROR: Trace: ProjectProvider: get Error: SQLITE_ERROR: no such table: project
--> in Database#all('SELECT id, name FROM project;', [], [Function (anonymous)])
    at .\Scripts\Services\DatabaseService.js:111:16
    at new Promise (<anonymous>)
    at DatabaseService.fetch (.\Scripts\Services\DatabaseService.js:109:16)
    at ProjectProvider.getAllProjects (.\Scripts\Providers\ProjectProvider.js:67:46)
    at loadLogsHandler (.\Scripts\handlers.js:40:28)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579) {
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}
    at ProjectProvider.getAllProjects (.\Scripts\Providers\ProjectProvider.js:74:21)
    at async loadLogsHandler (.\Scripts\handlers.js:40:19)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579)
2024-02-09T14:18:16.436Z DEBUG: main: Loading UI State
```

**Comment by madhaven** [comment]
It looks like the source filename while restoring from backups doesn't have a full file address.
```
ENOENT: no such file or directory, copyfile
at Object.copyFileSync
```

**Comment by madhaven** [comment]
Looks like it's working fine now
